### ISSUE TITLE
inconsistent variable naming conventions

### ISSUE THREAD

**Issue by RhysMP** [FTCTeam10298/2018-19-code#1]
man nathan do you even know camelCase? nathan fix it.

**Comment by qwertychouskie** [comment]
lol we were just talking about this in our discord

**Comment by RhysMP** [comment]
> lol we were just talking about this in our discord

Can you teach him camel case?

**Comment by qwertychouskie** [comment]
https://github.com/FTCTeam10298/2016-17-code/commit/231f280328c6e24b4b612c761c275a52e8e52d2a#diff-18c64df6ed13c42e31966626f166ea980ccb160d6b530bb157cefa7a612ec6b6R199

For shame @nathanmchoi, for shame
